### PR TITLE
Add missing includes, fix #18

### LINKED ISSUE #18: Missing includes
Hi,

This library does not compile with pinocchio v1.3.1:
> include/tsid/robots/robot-wrapper.hpp:113:32    : error: 'se3::Data::Matrix6x' has not been declared

### PR DESCRIPTION
**Pull request by nim65s**

### CODE REVIEW

**Comment by nim65s** [comment]
This leads to this error when we compile with the fix on pinocchio v1.2.9r2…
> include/tsid/robots/robot-wrapper.hpp:25:40: fatal error: pinocchio/multibody/data.hpp: No such file or directory

What's wrong ?

**Comment by nim65s** [comment]
So… Matrix6x was in `model.hpp` and has been moved to a new file `data.hpp` without any deprecation ?
