### ISSUE TITLE
demo_romeo does not run with latest pinocchio, gepetto-gui, gepetto-viewer-corba

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/tsid#26]
Likely due to a change in the Pinocchio API?

```
$ ipython demo/demo_romeo.py
####################################################################################################
################################# Test Task Space Inverse Dynamics #################################
#################################################################################################### 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/wxm/dev/pinocchio_ws/tsid/demo/demo_romeo.py in <module>()
     52 
     53 # for gepetto viewer .. but Fix me!!
---> 54 robot_display = se3.RobotWrapper(urdf, [path, ], se3.JointModelFreeFlyer())
     55 
     56 l = commands.getstatusoutput("ps aux |grep 'gepetto-gui'|grep -v 'grep'|wc -l")

/home/wxm/.local/lib/python2.7/site-packages/pinocchio/robot_wrapper.pyc in __init__(self, model, collision_model, visual_model, verbose)
     50 
     51         self.model = model
---> 52         self.data = self.model.createData()
     53 
     54         self.collision_model = collision_model

AttributeError: 'str' object has no attribute 'createData'
```

**Comment by andreadelprete** [comment]
The constructor of the python class `RobotWrapper` has changed interface. I think now we should use the static method `BuildFromURDF` (see [here](https://github.com/stack-of-tasks/pinocchio/blob/devel/bindings/python/scripts/robot_wrapper.py#L16)) to create a `RobotWrapper`, which has exactly the same interface of the old constructor of `RobotWrapper`. Could you try doing that @wxmerkt ?

**Comment by wxmerkt** [comment]
Fix in #27, bar segmentation fault issues on 18.04 with `gepetto-viewer-corba`.

**Comment by wxmerkt** [comment]
This now works on 18.04 with:
- `pinocchio` on `master` (even though we just discussed F2F pinocchio `devel` should match tsid `pinocchio_v2`)
- `tsid` on `pinocchio_v2`
- `gepetto-viewer` on `master`
- `gepetto-viewer-corba` on `master`
- Restarting the omniorb-nameserver a few times
- No DAE meshes, of course, as per the troubleshooting guide in `gepetto-viewer-corba`

**Comment by andreadelprete** [comment]
How can tsid on pinocchio_v2 be compatible with pinocchio on master (v 1.3) ?
